/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Address.book.using.json.gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
